module.exports = {
	INVALID_INPUT: 'vld_01',
	INTERNAL_SERVER_ERROR: 'srv_01',
	AUTH_ERRORS: {
		EMAIL_IN_USE: 'auth_01',
		TOKEN_EXPIRED: 'auth_02',
		TOKEN_INVALID: 'auth_03',
		USER_NOT_FOUND: 'auth_04',
		ALREADY_VERIFIED: 'auth_05',
		INVALID_CREDENTIALS: 'auth_06',
		NO_TOKEN_PROVIDED: 'auth_07',
	},
	USER_ERRORS: {
		USER_NOT_FOUND: 'usr_01',
		USER_PROFILE_NOT_FOUND: 'usr_02',
	},
	COMPANY_ERRORS: {
		ALREADY_JOB_POSTER: 'cmp_01'
	},
};